services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3309:3306" # Optional: expose MySQL to the host
    environment:
      MYSQL_DATABASE: database
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./libs/domain:/docker-entrypoint-initdb.d

volumes:
  mysql_data: